[package]
name = "mackes-midi-matrix"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mackes-config = { path = "../../crates/config" }
mackes-domain = { path = "../../crates/domain" }
mackes-tui = { path = "../../crates/tui" }
ratatui.workspace = true
crossterm.workspace = true
owo-colors.workspace = true
mackes-profiles = { path = "../../crates/profiles" }
mackes-midi-engine = { path = "../../crates/midi-engine" }
mackes-ipc = { path = "../../crates/ipc" }
mackes-scene-engine = { path = "../../crates/scene-engine" }
serde_json.workspace = true

[lints]
workspace = true

[[bin]]
name = "mackes-midi-matrix"
path = "src/main.rs"
